//redux types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE'; //singular
export const GET_PROFILES = 'GET_PROFILES'; //all
export const GET_FILMS = 'GET_FILMS';
export const CLEAR_FILMS = 'CLEAR_FILMS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_DISCUSSIONS = 'GET_DISCUSSIONS'; //all posts
export const DISCUSSION_ERROR = 'DISCUSSION_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_DISCUSSION = 'DELETE_DISCUSSION';
export const ADD_DISCUSSION = 'ADD_DISCUSSION';
export const GET_DISCUSSION = 'GET_DISCUSSION'; //singular
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
